# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='first_app.Course'),
            preserve_default=False,
        ),
    ]
