# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171126_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='users',
            field=models.ManyToManyField(related_name='quotes', to='first_app.User'),
        ),
    ]
