# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20171126_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='many_quotes', to='first_app.User'),
            preserve_default=False,
        ),
    ]
