# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20171121_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
