# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171126_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_by',
            new_name='liked_users',
        ),
    ]
