# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_product_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hired',
        ),
    ]
