# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
