# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20171130_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=200),
        ),
    ]
